/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface App {
  'id' : AppId,
  'name' : string,
  'createdAt' : Timestamp,
  'apkBlob' : ExternalBlob,
  'description' : string,
  'iconBlob' : ExternalBlob,
  'version' : string,
  'updatedAt' : Timestamp,
  'downloadCount' : bigint,
}
export type AppId = bigint;
export interface CreateAppArgs {
  'name' : string,
  'apkBlob' : ExternalBlob,
  'description' : string,
  'iconBlob' : ExternalBlob,
  'version' : string,
}
export type ExternalBlob = Uint8Array;
export type Timestamp = bigint;
export interface UpdateAppArgs {
  'id' : AppId,
  'name' : string,
  'apkBlob' : ExternalBlob,
  'description' : string,
  'iconBlob' : ExternalBlob,
  'version' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createApp' : ActorMethod<[CreateAppArgs], App>,
  'deleteApp' : ActorMethod<[AppId], boolean>,
  'getApp' : ActorMethod<[AppId], [] | [App]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'incrementDownload' : ActorMethod<[AppId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listApps' : ActorMethod<[], Array<App>>,
  'searchApps' : ActorMethod<[string], Array<App>>,
  'updateApp' : ActorMethod<[UpdateAppArgs], [] | [App]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];