/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateAppArgs = IDL.Record({
  'name' : IDL.Text,
  'apkBlob' : ExternalBlob,
  'description' : IDL.Text,
  'iconBlob' : ExternalBlob,
  'version' : IDL.Text,
});
export const AppId = IDL.Nat;
export const Timestamp = IDL.Int;
export const App = IDL.Record({
  'id' : AppId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'apkBlob' : ExternalBlob,
  'description' : IDL.Text,
  'iconBlob' : ExternalBlob,
  'version' : IDL.Text,
  'updatedAt' : Timestamp,
  'downloadCount' : IDL.Nat,
});
export const UpdateAppArgs = IDL.Record({
  'id' : AppId,
  'name' : IDL.Text,
  'apkBlob' : ExternalBlob,
  'description' : IDL.Text,
  'iconBlob' : ExternalBlob,
  'version' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApp' : IDL.Func([CreateAppArgs], [App], []),
  'deleteApp' : IDL.Func([AppId], [IDL.Bool], []),
  'getApp' : IDL.Func([AppId], [IDL.Opt(App)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'incrementDownload' : IDL.Func([AppId], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'searchApps' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
  'updateApp' : IDL.Func([UpdateAppArgs], [IDL.Opt(App)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateAppArgs = IDL.Record({
    'name' : IDL.Text,
    'apkBlob' : ExternalBlob,
    'description' : IDL.Text,
    'iconBlob' : ExternalBlob,
    'version' : IDL.Text,
  });
  const AppId = IDL.Nat;
  const Timestamp = IDL.Int;
  const App = IDL.Record({
    'id' : AppId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'apkBlob' : ExternalBlob,
    'description' : IDL.Text,
    'iconBlob' : ExternalBlob,
    'version' : IDL.Text,
    'updatedAt' : Timestamp,
    'downloadCount' : IDL.Nat,
  });
  const UpdateAppArgs = IDL.Record({
    'id' : AppId,
    'name' : IDL.Text,
    'apkBlob' : ExternalBlob,
    'description' : IDL.Text,
    'iconBlob' : ExternalBlob,
    'version' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApp' : IDL.Func([CreateAppArgs], [App], []),
    'deleteApp' : IDL.Func([AppId], [IDL.Bool], []),
    'getApp' : IDL.Func([AppId], [IDL.Opt(App)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'incrementDownload' : IDL.Func([AppId], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'searchApps' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
    'updateApp' : IDL.Func([UpdateAppArgs], [IDL.Opt(App)], []),
  });
};

export const init = ({ IDL }) => { return []; };